name: Greetings

on:
  push:
    # 分支随意
    branches:
      - master

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: greet
      run: |
           echo "hello"
           curl -X POST http://service-89uxytbj-1253286983.bj.apigw.tencentcs.com/release/visits_statistics
    
