name: Greetings

on:
  push:
    # 分支随意
    branches:
      - master

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: greet
      run: |
           echo "hello"
           curl -X GET http://service-jb5n0i6f-1253286983.bj.apigw.tencentcs.com/release/autoUp
    
